export {default as MenuItem} from './atoms/MenuItem'
export {default as SocialMediaBubble} from './atoms/SocialMediaBubble'
export {default as SlideMain} from './atoms/SlideMain'
export {default as Slide2} from './atoms/Slide2'
export {default as DateCard} from './atoms/DateCard'
export {default as Title} from './atoms/Title'
export {default as Slide} from './atoms/Slide'
export {default as Footer} from './atoms/Footer'

export {default as Menu} from './molecules/Menu'
export {default as Gallery} from './molecules/Gallery'
export {default as Dates} from './molecules/Dates'
export {default as LastRelease} from './molecules/LastRelease'
export {default as Bio} from './molecules/Bio'
